const PDFDocument = require('pdfkit');
const { formatDate, formatCurrency } = require('../helpers/formatters');
const { calculateSummaryStats } = require('../helpers/calculations');

const generatePDFReport = (trades, userName = 'Trader') => {
  const doc = new PDFDocument({ margin: 40, size: 'A4', layout: 'landscape' });
  const stats = calculateSummaryStats(trades);

  doc.fontSize(22).font('Helvetica-Bold').fillColor('#6366F1')
    .text('Swing Trading Journal Report', { align: 'center' });
  doc.moveDown(0.3);
  doc.fontSize(10).font('Helvetica').fillColor('#6B7280')
    .text(`Generated: ${formatDate(new Date())} | Trader: ${userName}`, { align: 'center' });
  doc.moveDown(1);

  doc.fontSize(14).font('Helvetica-Bold').fillColor('#111827').text('Performance Summary');
  doc.moveDown(0.5);
  doc.fontSize(10).font('Helvetica').fillColor('#374151');
  [
    `Total Trades: ${stats.totalTrades}`, `Win Rate: ${stats.winRate}%`,
    `Total P&L: ${formatCurrency(stats.totalProfitLoss)}`,
    `Avg Gain: ${formatCurrency(stats.averageGain)}`, `Avg Loss: ${formatCurrency(stats.averageLoss)}`,
    `Profit Factor: ${stats.profitFactor}`, `Avg Holding Days: ${stats.averageHoldingDays}`,
  ].forEach((item) => doc.text(`  •  ${item}`));
  doc.moveDown(1);

  doc.fontSize(14).font('Helvetica-Bold').fillColor('#111827').text('Trade Details');
  doc.moveDown(0.5);

  const headers = ['#','Stock','Type','Entry','Exit','Qty','P&L','Ret%','Status','Strategy'];
  const colW = [25,75,45,70,70,40,75,60,55,80];
  const startX = 40;
  let y = doc.y, x = startX;

  doc.rect(startX, y, colW.reduce((a,b)=>a+b,0), 18).fill('#6366F1');
  doc.fontSize(8).font('Helvetica-Bold').fillColor('#FFFFFF');
  headers.forEach((h,i) => { doc.text(h, x+3, y+5, {width:colW[i]-6}); x+=colW[i]; });
  y += 18;

  doc.font('Helvetica').fontSize(7);
  const maxR = Math.min(trades.length, 40);
  for (let i = 0; i < maxR; i++) {
    const t = trades[i];
    if (y > 540) { doc.addPage(); y = 40; }
    doc.rect(startX, y, colW.reduce((a,b)=>a+b,0), 16).fill(i%2===0?'#F9FAFB':'#FFFFFF');
    x = startX;
    const row = [`${i+1}`,t.stockName,t.tradeType.toUpperCase(),formatDate(t.entryDate),
      formatDate(t.exitDate),`${t.quantity}`,`${t.profitLoss>=0?'+':''}${t.profitLoss.toFixed(2)}`,
      `${t.returnPercentage.toFixed(2)}%`,t.status.toUpperCase(),t.strategy||'Manual'];
    row.forEach((c,j) => {
      let clr = '#374151';
      if (j===6) clr = t.profitLoss>=0?'#10B981':'#EF4444';
      if (j===8) clr = t.status==='win'?'#10B981':'#EF4444';
      doc.fillColor(clr).text(c, x+3, y+4, {width:colW[j]-6}); x+=colW[j];
    });
    y += 16;
  }
  if (trades.length > maxR) {
    doc.moveDown(1).fontSize(9).fillColor('#6B7280')
      .text(`... and ${trades.length-maxR} more trades.`, startX);
  }
  doc.moveDown(2).fontSize(8).fillColor('#9CA3AF')
    .text('Generated by Swing Trading Journal', { align: 'center' });
  return doc;
};

module.exports = { generatePDFReport };
